### ISSUE TITLE
NameError: name 'queryset' is not defined

### ISSUE THREAD

**Issue by hyzl-4869** [mangye16/DDAG#1]
Excuse me.
When I test on Regdb , there is a NameError that"name 'queryset' is not defined"
How can I solve it? Thank you!!!!

Traceback (most recent call last):
  File "test_ddag.py",line 152, in <module>
     query_loader = data.DataLoader(queryset, batchsize=args.test_batch, shuffle=False, num_workers=4)
NameError: name 'queryset' is not defined

**Comment by mangye16** [comment]
Can you successfully train on RegDB?

You may refer to the [test.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/test.py) for the testing on RegDB. I will update the "test_ddag.py" soon.

**Comment by hyzl-4869** [comment]
> Can you successfully train on RegDB?
> 
> You may refer to the [test.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/test.py) for the testing on RegDB. I will update the "test_ddag.py" soon.

Yes.I can train on RegDB successfully.But I can not test on it by test_ddag.py.
I tried to modify the code and  can test successfully, but I don't think the code is perfect.

**Comment by mangye16** [comment]
Sorry for the caused inconvenience. I may optimize the code soon.
